#!/bin/bash
# Prueft ob Datei juenger oder aelter als 28h.
# Sven Rath - 16.08.2018

#This script is provided under the MIT License
#
#Copyright (c) [2018] [Sven Rath]
#
#Contact
#E-Mail: sven.rath@mail.de
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.



# Setzt max Alter auf 28h
MAXAGE=$(bc <<< '28*60*60') # seconds in 28 hours

# Prueft wie alt  die Date ist
FILEAGE=$(($(date +%s) - $(stat -c '%Y' " !!!!!!!!_______PATHTOFILE_____!!!!!!!!!")))


if [[ $FILEAGE -lt $MAXAGE ]]; then
     status=0
else status=2
fi

if [[ $status != 0 ]];then
                alarm=2:2:"FEHLERMELDUNG: $host"
            else    alarm=0:0:"ALLES OK MELDUNG"
        fi

echo $alarm
